[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Olivia Kaufman <akaritakai@gmail.com>"]
edition = "2021"

[dependencies]
reqwest = {version = "0.11", features = ["blocking"]}

[dev-dependencies]
httpmock = "0.6"
rand = "0.8"
tempfile = "3.8"
