FROM rust:1.73.0

RUN rustup component add llvm-tools-preview
RUN cargo install grcov

ENV CARGO_INCREMENTAL=0
ENV RUSTFLAGS="-C instrument-coverage"
ENV LLVM_PROFILE_FLAG="/opt/aoc/coverage/%p-%m.profraw"

WORKDIR /opt/aoc
COPY . .
RUN cargo test --release

RUN grcov . --binary-path ./target/release/ -s . -t lcov --branch --ignore-not-existing -o lcov.info
