FROM rust:latest

RUN apt-get update && \
    apt-get install -y \
      libclang-dev \
      libz3-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR "/opt/aoc"
COPY . .

RUN rustup component add llvm-tools-preview
RUN cargo install grcov

ENV CARGO_INCREMENTAL=0
ENV RUSTFLAGS="-C instrument-coverage"
ENV LLVM_PROFILE_FLAG="/opt/aoc/coverage/%p-%m.profraw"

RUN cargo test --release
RUN grcov . --binary-path ./target/release/ -s . -t lcov --branch --ignore-not-existing -o lcov.info
